language: python
python:
  - "3.6"
install:
  - pip install -e ".[tests]"
script:
  - python -m unittest
  - pycodestyle shared_schema
  - pycodestyle test
  - flake8 shared_schema
  - flake8 test
notifications:
  email:
    on_error: change
